### ISSUE TITLE
PhoneGap Build Failed (iOS)

### ISSUE THREAD

**Issue by juankza95** [jleszczynski/cordova-vr-player#1]
**Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-vr-player**

The log says:

`#####/Plugins/cordova-vr-player/VideoPlayerViewController.m:5:9: fatal error: 'GVRVideoView.h' file not found
#import "GVRVideoView.h
          ^
1 error generated."`

I'm using the plugin from npm (should be 1.3.0 I think, and the user's name is similar) but Phonegap Build is using 1.2.0

On Android works well, thanks!

**Comment by binoculars88** [comment]
@juankza how did you manage to make this work on Android? I'm using it in Ionic. The player loads but it says "file not found". I've copied to video file everywhere... nothing seems to work.

**Comment by georgski** [comment]
Hi @juankza, apologies for not getting back sooner.
The error indicates that the Google VR SDK is missing. It's quite odd as normally the GVRSDK cocoapod, should be installed automatically upon plugin installation (it's handled by [cordova-plugin-cocoapods-support](https://github.com/Aerex/cordova-plugin-cocoapods-support/) plugin).
Could you please try installing the [GVRSDK ](https://cocoapods.org/pods/GVRSDK)pod manually (version 1.0.1) to see if that helps?

**Comment by binoculars88** [comment]
Does this mean `cordova-plugin-cocoapod-support` should be installed first, before installing `cordova-vr-player`, in order to make it work on iOS?

Edit: tried it again from scratched, but installed cocoapod first. Works like a charm!

**Comment by georgski** [comment]
The `cordova-plugin-cocoapod-support` is listed as a dependency in [plugin.xml](https://github.com/jleszczynski/cordova-vr-player/blob/master/plugin.xml#L11) so it _should_ be installed automatically upon plugin installation. I wonder why it didn't work, sorry but I don't have enough time at the moment to investigate this further. Perfect, glad it worked!

**Comment by juankza95** [comment]
I don't know why PhoneGap Build doesn't install the cocoapod dependency.

Btw, in Android worked and I tried only be streaming a video from a server. I was only investigating at all. Great plugin man!

**Comment by arkadiuszkubaczkowski** [comment]
@binoculars88 I have the same problem, could you explain me how did u make it works?
