### ISSUE TITLE
Where to put video file?

### ISSUE THREAD

**Issue by binoculars88** [jleszczynski/cordova-vr-player#2]
Where do I put the video file? I'm using Ionic 2 and put the video in the same folder as the file where I've put `GoogleVRPlayer.playVideo('shark.mp4');` , but this gives me an error after the player opens up:

> Error loading video: com.google.android.exoplayer.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: shark.mp4: open failed: ENOENT (No such file or directory).

Any thoughts?

**Comment by georgski** [comment]
Hi, sorry the plugin isn't properly documented, but playVideo accepts an absolute path as a parameter.
For example, to play a video stored in your app's www directory, you can use the following code (it requires Cordova File Plugin to be installed):

```
var path = cordova.file.applicationDirectory + 'www/video.mp4';
GoogleVRPlayer.playVideo(path);
```

**Comment by binoculars88** [comment]
Thanks! The error is gone and the video starts to play. However, there's a calibration problem. As a demo, I'm using the video from [Google's dev page](https://storage.googleapis.com/vrview/examples/video/index.html). In the app, it looks like [this](https://ibb.co/ehsGy5). As you can see, the floor and the sky are stitched together in the center. Any idea how to fix this?

**Comment by georgski** [comment]
The [VRVideoView](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/video/VrVideoView.Options.html#inputType) by default expects the video to be a monocular panorama. We ideally should pass this option as parameter, but temporarily you can put the following code [here](https://github.com/jleszczynski/cordova-vr-player/blob/master/src/android/java/neotrino/VrVideoActivity.java#L210) to support stereoscopic videos:

```
VrVideoView.Options options = new VrVideoView.Options();
options.inputType = VrVideoView.Options.TYPE_STEREO_OVER_UNDER;
videoWidgetView.loadVideo(fileUri, options);
```

**Comment by binoculars88** [comment]
Thanks!!! Works like a charm on both Android and iOS! Awesome plugin!

**Comment by georgski** [comment]
Thank you, glad it worked! Any pull requests are most welcome.
